# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-15 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('farmerID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('localAddress', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phoneNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('paymentID', models.AutoField(primary_key=True, serialize=False)),
                ('DOP', models.DateField()),
                ('Price', models.IntegerField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectionmanager.Farmers')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('DOD', models.DateField()),
                ('quantity', models.IntegerField()),
                ('storageHygiene', models.CharField(choices=[('1', 'PASS'), ('0', 'FAIL')], max_length=10)),
                ('bacterialScreening', models.CharField(choices=[('1', 'PASS'), ('0', 'FAIL')], max_length=10)),
                ('fatContent', models.IntegerField()),
            ],
        ),
    ]
